### PR TITLE
Updates and fixes

### PR DESCRIPTION
**Pull request by PiKeyAr**
Summary of changes:

- Account for original models in OnFrame checks - should help with #27

- Small code optimizations in the OnFrame checks

- Various structural changes/updates. Upgraded the build tools to v141_xp, updated the Mod Loader to the latest version, renamed DC vertex indices to avoid conflicts with new Mod Loader pointers, added project dependencies for libmodutils and ModLoaderCommon so it will be easier to upgrade the Mod Loader in the future. Also changed project configuration to output debug and release builds into the "bin" folder for consistency with libmodutils/ModLoaderCommon .

- Added more Lantern fixes for EV Tornado 2 (found a missing material during a palette test playthrough)

- Suppressed warnings in header files - the mod should now build a bit faster and without warnings

- Fixed the ReplacePVM macro, which is called in the mod with two arguments but was using only one argument in the macro, resulting in a warning during compilation.

- Removed some Lantern API fixes related to Gamma's upgrades (see comment)

### CODE REVIEW

**Comment by PiKeyAr** [comment]
One more thing. I removed Lantern API hooks for Gamma's Jet Booster and Laser Scope. After testing the behavior in SA1 and double-checking in SADX, I found out that these upgrades aren't always using the level/object light type even in the original game because they are drawn using a different function that doesn't force a light type (same as some upgrades for other characters). With the fix, the only time these models were lit correctly was the character select screen. I removed these fixes earlier in Lantern Engine for the same reason.

**Comment by PiKeyAr** [comment]
Another update: I've removed Lantern API materials for Big's rod upgrade because it's inaccurate
image
The rod picks up the correct light type automatically when it switches to the cutscene anyway
image

**Comment by ItsEasyActually** [comment]
For the sake of keeping the character stuff together, I would prefer it getting added to this mod as well. If you want to toss it in there before I merge this pull in, feel free to. I'll be merging it by the end of today as long as I don't get too busy with other things.

**Comment by PiKeyAr** [comment]
Alright, I'll move over a few other transparency and lighting fixes there as well then!

**Pull request merged**
